### PR TITLE
Added foreign keys to pilot

### PR DESCRIPTION
**Pull request by NickolausDS**
Feature for #105 
Added the feature to include random foreign keys to new entries on register/upload. The style looks like this:
```
pilot upload foo.txt / --foreign-keys mykeys.json
```
where `mykeys.json` is:
```
{
  "TestThing": {
    "reference": {
      "filename": "the test file",
      "resource": "foo.txt",
      "fields": "sample_name"
    }
  }
}
```
An example is here: https://petreldata.net/nci-pilot1-test/projects/nick-testing/globus%253A%252F%252Febf55996-33bf-11e9-9fa4-0a06afd4a22e%252Fprojects%252Fnick-testing%252Ftest_file.tsv/

I didn't get to finish tests for this. The changes are in two parts: implementing this feature, and refactoring the previous ugly code which badly implemented this feature. The old feature required building the URLs from the references.json file and so passed the client down into `search.py` in order to do so. The new feature instead better understands how analytics works, and will swap the short paths with the real URL before the metadata is ingested.

### CODE REVIEW

**Comment by rpwagner** [comment]
Given a file `TestThing.csv` in a dataset, show that the column `foo` in `TestThing.csv` has metadata listed in a file in another dataset. Perhaps like so:
```
{
  `TestThing.csv`: {
      `foo`: `PathToOtherDataset#MetdataFile.csv`
    }
}
```

**Comment by NickolausDS** [comment]
@rpwagner The spec change makes sense. Did you want to also include foreign keys in the metadata file, or keep it as a separate JSON file?

**Comment by rpwagner** [comment]
I think having it in the metadata file is preferred, but pick what's cleanest.

**Comment by NickolausDS** [comment]
I'll include it in the metadata file, I think that will be cleaner as well. 

Unrelated to foreign-keys, I found the current way pilot handles metadata to be a little cumbersome when updating existing records. This is due to pilot preferring users to specify metadata in a flat dict, but it's returned by pilot nested by `files`, `dc`, and `project-metadata`. My irritation may also be because of #93 and #94. Is this something we might want to change? 

Here's an example:
user.json: 
```
{"description": "My description"}
```
Usage: `pilot upload mydataset --json user.json`

Json returned by Pilot is different (eg `pilot describe mydataset --json`), making updating it a pain. The `dc` key needs to be removed to make it flat again.
```
{"dc": {"description": "My description"}}
```

**Comment by rpwagner** [comment]
I agree, I prefer results of `describe` to be something that can be edited and reused for the same or different datasets. And having examples for each project or context makes that a lot easier for the user.

**Comment by NickolausDS** [comment]
Created an issue here #120

**Comment by NickolausDS** [comment]
These changes are not needed anymore. They may get picked up again in the future, but as of now are out of date and could in general could use a bit more work to make sure they're easy to specify

**Pull request closed without merging**
