### PR TITLE
[WIP] Project overhaul: Now supports multiple projects

### PR DESCRIPTION
**Pull request by NickolausDS**
This contains the bulk of the functionality we need to support multiple projects. I haven't rewritten the tests, and these changes touch everything, so there is very likely some breakage. 

* Changes include:
    * Switching to ConfigObj -- this is needed to store project information, which doesn't neatly fit within config parser due to not supporting saving nested dictionaries
    *  Supporting a Global project settings json file (not currently in use)
        * We can store this on the endpoint somewhere under /projects
        * Checks and notifies people once per day if somebody has updated the master list
    * Supports switching projects
    * Supports an arbitrary number of new projects
    * Adding an endpoint agnostic HTTP client
    * Built-in migration to the newer config library from using the older lib
    * a version update to 0.2.0.dev

* Upcoming Changes::
    * **Fix the tests!**
    * `pilot project create` command
    * `pilot project info` command

### CODE REVIEW

**Comment by rpwagner** [comment]
I'm testing this and I got the following:

```
(base) Magik:~ rpwagner$ pilot whoami
Traceback (most recent call last):
  File "/Users/rpwagner/anaconda3/bin/pilot", line 10, in <module>
    sys.exit(cli())
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pilot/commands/main.py", line 14, in cli
    pc = get_pilot_client()
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pilot/commands/__init__.py", line 5, in get_pilot_client
    return PilotClient()
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pilot/client.py", line 30, in __init__
    self.project = project.Project(self)
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pilot/project.py", line 38, in __init__
    super().__init__()
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pilot/config.py", line 72, in __init__
    self.save_option(self.SECTION, {})
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/pilot/config.py", line 76, in save_option
    cfg[section or self.SECTION][option] = value
  File "/Users/rpwagner/anaconda3/lib/python3.7/site-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'project'
```

**Comment by NickolausDS** [comment]
I hastily fixed some bugs, which should at least let you see how the `project` subcommand works. These changes are still pretty unstable, and I wouldn't advise using them until I get the tests done.

**Comment by NickolausDS** [comment]
The latest update adds the `pilot project add` interactive command. @rpwagner You may need to do a pilot logout --purge, I think there was a bug in the config between one of the commits here. People with older configs will see them get automatically updated to the newest version. 

Next, I'll add the `pilot project info` and `pilot project push` commands.

**Comment by rpwagner** [comment]
@NickolausDS I'm going to merge this for testing.

**Comment by NickolausDS** [comment]
A couple things still remain, mainly:

* Adding 'push' functionality to update projects for all users (Should be done soon)
* Fixing 'download' (should be done soon)
* Removing required metadata fields (should be done soon)
* Adding tests for upload/download/projects (I'm going to wait on these and start on the portal)

I'll go ahead and push new changes to master.

**Pull request merged**
