### PR TITLE
Multi-File Dataframe Handling

### PR DESCRIPTION
**Pull request by NickolausDS**
This is a prototype for uploading a directory in addition to a
file. Uploading a directory recursively uploads all files within
that directory, analyzing each file and determining its mimetype.

Currently, the prototyped changes only support the following:

`pilot upload mydirectory /`

All other invocations will likely break in unexpected ways.

The above command creates the search entry
'projects/my-project/mydirectory', and recursively transfers all
files. The search entry contains hashes for each file. This will
change a little bit for HDF5 (I don't think it's feasible to hash
files within an hdf5 store), but this should be enough to start
prototyping similar changes on the portal.

### CODE REVIEW

**Comment by rpwagner** [comment]
@NickolausDS HDF5 is still a single file, but with structured data inside of it. It's fine to only hash the HDF5 file.

**Comment by NickolausDS** [comment]
Hmm, how should the file manifests look? HDF5 is technically one file, I think it would break the remote_file_manifest spec to have each internal file be a separate file-manifest entry. Should HDF5 be a special edge case where we show extra file metadata for HDF5 within the single entry? That might look like this:

```
[
  {
    "filename": "foo.hdf5",
    "length": 12345678,
    "md5": "9c5a9facb3c2af4f2afa8ea5a900a929",
    "mime_type": "application/x-hdf",
    "sha256": "644a79156fe67292184ca718e7324eb39dcacc9fae0814c84d3056abdf5bee6e",
    "url": "https://ebf55996-33bf-11e9-9fa4-0a06afd4a22e.e.globus.org/projects/nick-testing/foo.hdf5",
    "internal_files": [
      {
        "filename": "bar.csv",
        "mime_type": "text/csv",
        "field_metadata": {
          "field_definitions": [
            {
              "count": 99,
              "format": "default",
              "frequency": 99,
              "name": "firstrow",
              "top": "firstrow",
              "type": "string",
              "unique": 1
            }
          ]
        }
      }
    ]

  }
]
```

**Comment by rpwagner** [comment]
HDF5 has its own naming schema for various objects and structures in the file. For the most part, there are groups (`/`, `/foo/`) and datasets (`/array1`, `/foo/array2`). It's important to be clear that these are not separate files, but arrays, datasets, or dataframes within the file. And the term dataset is also a problem, because we use that to refer to a collection of files.

**Comment by NickolausDS** [comment]
For now, can I concentrate on adding features to upload multiple files within a directory? After that, we could look a little more closely at HDF5 and replicate similar behavior as directories, does that sound good?

**Comment by rpwagner** [comment]
Yes, focus on handling files within a directory. Just treat the HDF5 as a single file. Then we'll go back and have some features to pull out dataframe metadata from within an HDF5 file.

**Comment by NickolausDS** [comment]
Ok, this should be good to go. `pilot upload mydir /` should work where `mydir` contains a ton of different types of files and directories. `pilot describe` will show files within the collection, and `pilot download` understands which file you're talking about if you say `pilot download mydir/foo/bar.txt`. Maybe one of the final touches would be updating the `docs` to include an example multi-file directory.

**Comment by NickolausDS** [comment]
Next up is support for showing various objects in HDF5.

**Pull request merged**
